/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Models.PhongDAO;
import Utils.ClickMouse;
import Utils.MapRoom;
import java.awt.Color;
import java.awt.Component;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.GridBagConstraints;
import java.awt.event.MouseAdapter;
import javax.swing.JPanel;

/**
 *
 * @author you have to better
 */
public class ManHinhChinhGUI extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhChinhGUI
     */
    public static boolean switchSize;
    GridBagConstraints gbc;
    PhongDAO phongDAO;

    public ManHinhChinhGUI() {
        initComponents();
        setTitle("Quản lý khách sạn");
        setLocationRelativeTo(this);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlSlider = new javax.swing.JPanel();
        lblQuanLyKhacSan = new javax.swing.JLabel();
        pnlSeparator = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHoaDon = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnQuanLyPhong = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnNhanVien = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnDichVu = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnThongKe = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnPhanHoi = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ScpScreenDisplay = new javax.swing.JScrollPane();
        pnlScreen = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(247, 22, 52));

        pnlSlider.setBackground(new java.awt.Color(247, 22, 52));
        pnlSlider.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuanLyKhacSan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblQuanLyKhacSan.setForeground(new java.awt.Color(204, 204, 204));
        lblQuanLyKhacSan.setText("QUẢN LÝ KHÁCH SẠN");
        pnlSlider.add(lblQuanLyKhacSan, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 23, -1, -1));

        pnlSeparator.setBackground(new java.awt.Color(204, 204, 204));
        pnlSeparator.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout pnlSeparatorLayout = new javax.swing.GroupLayout(pnlSeparator);
        pnlSeparator.setLayout(pnlSeparatorLayout);
        pnlSeparatorLayout.setHorizontalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlSeparatorLayout.setVerticalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        pnlSlider.add(pnlSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 88, 301, -1));

        btnHome.setBackground(new java.awt.Color(247, 22, 52));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
        });
        btnHome.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 24, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_home_50px.png"))); // NOI18N
        btnHome.add(jLabel1);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HOME");
        btnHome.add(jLabel2);

        pnlSlider.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 330, 70));

        btnHoaDon.setBackground(new java.awt.Color(247, 22, 52));
        btnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHoaDonMousePressed(evt);
            }
        });
        btnHoaDon.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 24, 5));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_bill_50px.png"))); // NOI18N
        btnHoaDon.add(jLabel3);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("HÓA ĐƠN");
        btnHoaDon.add(jLabel4);

        pnlSlider.add(btnHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 330, 70));

        btnQuanLyPhong.setBackground(new java.awt.Color(247, 22, 52));
        btnQuanLyPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLyPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLyPhongMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQuanLyPhongMousePressed(evt);
            }
        });
        btnQuanLyPhong.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 24, 5));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_room_50px.png"))); // NOI18N
        btnQuanLyPhong.add(jLabel5);

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("QUẢN LÝ PHÒNG");
        btnQuanLyPhong.add(jLabel6);

        pnlSlider.add(btnQuanLyPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 330, 70));

        btnNhanVien.setBackground(new java.awt.Color(247, 22, 52));
        btnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNhanVienMousePressed(evt);
            }
        });
        btnNhanVien.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 24, 5));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_people_50px.png"))); // NOI18N
        btnNhanVien.add(jLabel7);

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("NHÂN VIÊN");
        btnNhanVien.add(jLabel8);

        pnlSlider.add(btnNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 330, 70));

        btnDichVu.setBackground(new java.awt.Color(247, 22, 52));
        btnDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDichVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDichVuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDichVuMousePressed(evt);
            }
        });
        btnDichVu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 24, 5));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_service_bell_50px.png"))); // NOI18N
        btnDichVu.add(jLabel9);

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DỊCH VỤ");
        btnDichVu.add(jLabel10);

        pnlSlider.add(btnDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 330, 70));

        btnThongKe.setBackground(new java.awt.Color(247, 22, 52));
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongKeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnThongKeMousePressed(evt);
            }
        });
        btnThongKe.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 24, 5));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_activity_history_50px.png"))); // NOI18N
        btnThongKe.add(jLabel11);

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("THỐNG KÊ");
        btnThongKe.add(jLabel12);

        pnlSlider.add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 330, 70));

        btnPhanHoi.setBackground(new java.awt.Color(247, 22, 52));
        btnPhanHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPhanHoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPhanHoiMouseExited(evt);
            }
        });
        btnPhanHoi.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 24, 5));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_ask_question_50px.png"))); // NOI18N
        btnPhanHoi.add(jLabel13);

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("PHẢN HỒI");
        btnPhanHoi.add(jLabel14);

        pnlSlider.add(btnPhanHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 330, 70));

        jPanel4.setBackground(new java.awt.Color(212, 34, 51));

        pnlScreen.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlScreenLayout = new javax.swing.GroupLayout(pnlScreen);
        pnlScreen.setLayout(pnlScreenLayout);
        pnlScreenLayout.setHorizontalGroup(
            pnlScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1167, Short.MAX_VALUE)
        );
        pnlScreenLayout.setVerticalGroup(
            pnlScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );

        ScpScreenDisplay.setViewportView(pnlScreen);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScpScreenDisplay)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScpScreenDisplay, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(pnlSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        changeColor(btnHome);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        resetColor(btnHome);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseEntered
        // TODO add your handling code here:
        changeColor(btnHoaDon);
    }//GEN-LAST:event_btnHoaDonMouseEntered

    private void btnHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseExited
        // TODO add your handling code here:
        resetColor(btnHoaDon);
    }//GEN-LAST:event_btnHoaDonMouseExited

    private void btnQuanLyPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyPhongMouseEntered
        // TODO add your handling code here:
        changeColor(btnQuanLyPhong);
    }//GEN-LAST:event_btnQuanLyPhongMouseEntered

    private void btnQuanLyPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyPhongMouseExited
        // TODO add your handling code here:
        resetColor(btnQuanLyPhong);
    }//GEN-LAST:event_btnQuanLyPhongMouseExited

    private void btnNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseEntered
        // TODO add your handling code here:
        changeColor(btnNhanVien);
    }//GEN-LAST:event_btnNhanVienMouseEntered

    private void btnNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseExited
        // TODO add your handling code here:
        resetColor(btnNhanVien);
    }//GEN-LAST:event_btnNhanVienMouseExited

    private void btnDichVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichVuMouseEntered
        // TODO add your handling code here:
        changeColor(btnDichVu);
    }//GEN-LAST:event_btnDichVuMouseEntered

    private void btnDichVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichVuMouseExited
        // TODO add your handling code here:
        resetColor(btnDichVu);
    }//GEN-LAST:event_btnDichVuMouseExited

    private void btnThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseEntered
        // TODO add your handling code here:
        changeColor(btnThongKe);
    }//GEN-LAST:event_btnThongKeMouseEntered

    private void btnThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseExited
        // TODO add your handling code here:
        resetColor(btnThongKe);
    }//GEN-LAST:event_btnThongKeMouseExited

    private void btnPhanHoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhanHoiMouseEntered
        // TODO add your handling code here:
        changeColor(btnPhanHoi);
    }//GEN-LAST:event_btnPhanHoiMouseEntered

    private void btnPhanHoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhanHoiMouseExited
        // TODO add your handling code here:
        resetColor(btnPhanHoi);
    }//GEN-LAST:event_btnPhanHoiMouseExited

    private void btnDichVuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichVuMousePressed
        // TODO add your handling code here:
        JPanel dichvu = new DichVuPanel();
        SwitchPanel(dichvu);
    }//GEN-LAST:event_btnDichVuMousePressed

    private void btnThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMousePressed
        // TODO add your handling code here:
        JPanel lichSuGD = new LichSuGDPanel();
        SwitchPanel(lichSuGD);
        System.out.println("lay out" + pnlScreen.getLayout().toString());
    }//GEN-LAST:event_btnThongKeMousePressed

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        // TODO add your handling code here:
        fillToHome();
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnQuanLyPhongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyPhongMousePressed
        // TODO add your handling code here:
        JPanel quanLyPhong = new QuanLyPhongPanel();
        SwitchPanel(quanLyPhong);
    }//GEN-LAST:event_btnQuanLyPhongMousePressed

    private void btnHoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMousePressed
        // TODO add your handling code here:
        JPanel hoaDon = new QuanLyHoaDonPanel();
        SwitchPanel(hoaDon);
    }//GEN-LAST:event_btnHoaDonMousePressed

    private void btnNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMousePressed
        // TODO add your handling code here:
        NhanVienJFrame nv = new NhanVienJFrame();
        nv.setVisible(true);
    }//GEN-LAST:event_btnNhanVienMousePressed

    public void init() {
        phongDAO = new PhongDAO();
        gbc = new GridBagConstraints();
        switchSize = true;
        ScpScreenDisplay.getVerticalScrollBar().setUnitIncrement(16);
        MapRoom.setGridBagLayout(gbc, pnlScreen);
        fillToHome();
    }

    public void fillToHome() {
        resetStatus();
        JPanel home = new HomePanel();
        SwitchPanel(home);
    }
    
    public void resetStatus(){
        phongDAO.updateMaTT3();
    }

    // thay đổi giao diện hiển thị trong panel pnlScreen
    public void SwitchPanel(JPanel panel) {

        pnlScreen.removeAll();
        panel.setVisible(true);
        MapRoom.setGridBagLayout(gbc, pnlScreen);
        panel.setAlignmentX(Component.LEFT_ALIGNMENT);
        pnlScreen.add(panel);
        pnlScreen.revalidate();
        pnlScreen.repaint();
    }

    public void changeColor(JPanel panel) {
        panel.setBackground(new Color(224, 70, 84));
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new Color(247, 22, 52));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhChinhGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScpScreenDisplay;
    private javax.swing.JPanel btnDichVu;
    private javax.swing.JPanel btnHoaDon;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnNhanVien;
    private javax.swing.JPanel btnPhanHoi;
    private javax.swing.JPanel btnQuanLyPhong;
    private javax.swing.JPanel btnThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblQuanLyKhacSan;
    private javax.swing.JPanel pnlScreen;
    private javax.swing.JPanel pnlSeparator;
    private javax.swing.JPanel pnlSlider;
    // End of variables declaration//GEN-END:variables
}
