/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entities.HoaDon;
import Entities.HoaDonChiTiet;
import Entities.KhachHang;
import Entities.LichSuGD;
import Entities.LoaiThanhToan;
import Entities.Phong;
import Entities.ThanhToan;
import Models.DichVuDAO;
import Models.HoaDonChiTietDAO;
import Models.HoaDonDAO;
import Models.KhachHangDAO;
import Models.LichSuGDDAO;
import Models.LoaiPhongDAO;
import Models.LoaiThanhToanDAO;
import Models.PhongDAO;
import Models.ThanhToanDAO;
import Models.YeuCauDAO;
import Utils.MapRoom;
import Utils.mgsBox;
import Utils.xMoney;
import Utils.xTime;
import java.math.BigDecimal;
import java.math.MathContext;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author you have to better
 */
public class TraPhongJpanel extends javax.swing.JPanel {

    /**
     * Creates new form TraPhongJpanel
     */
    LichSuGDDAO lichSuGDDAO;
    KhachHangDAO khachHangDAO;
    HoaDonDAO hoaDonDAO;
    HoaDonChiTietDAO hoaDonChiTietDAO;
    LichSuGDDAO lsgddao;
    PhongDAO phongDAO;
    LoaiPhongDAO loaiPhongDAO;
    YeuCauDAO yeuCauDAO;
    DichVuDAO dichVuDAO;
    ThanhToanDAO thanhToanDAO;
    LoaiThanhToanDAO loaiThanhToanDAO;
    public static int maKH;
    public static float sumHour;
    public static int sumMinute;
    public static int sumDay;
    public static double sumMoneyRoom;
    public static double sumMoneyService;
    public static double sumMoneyHavePay;
    public static double tienTraCham;
    public static double tienVaoSom;
    public static double tienPhuThu;
    public static double tienTraTruoc;
    public static double tienGiamGia;
    public static double tienKhuyenMai;
    public static double tienPhucVuNGayLe;

    public TraPhongJpanel(int maKH) {
        initComponents();
        this.maKH = maKH;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jdcCheckIn = new com.toedter.calendar.JDateChooser();
        txtGioCheckIn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPhutCheckIn = new javax.swing.JTextField();
        jdcCheckOut = new com.toedter.calendar.JDateChooser();
        txtGioCheckOut = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPhutCheckOut = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQuocTich = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        lblCMT = new javax.swing.JLabel();
        txtSoCMT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cboGioiTinh = new javax.swing.JComboBox<>();
        jPanel16 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtSoDT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jdcNgaySinh = new com.toedter.calendar.JDateChooser();
        jPanel17 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtQueQuan = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        chkTheoNgay = new javax.swing.JCheckBox();
        chkTheoGio = new javax.swing.JCheckBox();
        jPanel18 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongTinPhong = new javax.swing.JTable();
        txtSoPhong = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtSoTang = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTongTienDichVu = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblTongTienPhong = new javax.swing.JLabel();
        txtTienTheoGio = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtSoGio = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtTienTheoNgay = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtSoNgay = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtTongTienPhong = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblTongTienDV = new javax.swing.JLabel();
        txtTongTienDichVu = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        lblTongPhiPhuThu = new javax.swing.JLabel();
        txtPhiPhuThu = new javax.swing.JTextField();
        lblPhiTraPhongMuon = new javax.swing.JLabel();
        txtPhiTraPMuon = new javax.swing.JTextField();
        lblPhiNhanPhongSom = new javax.swing.JLabel();
        txtPhiNhanPSom = new javax.swing.JTextField();
        lblPhiDVNgayLe = new javax.swing.JLabel();
        cboPhiDVNgayLe = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        lblKhuyenMai = new javax.swing.JLabel();
        cboKhuyenMai = new javax.swing.JComboBox<>();
        lblTraTruoc = new javax.swing.JLabel();
        txtTraTruoc = new javax.swing.JTextField();
        lblGiamGia = new javax.swing.JLabel();
        txtGiamGia = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        lblLoaiThanhToan = new javax.swing.JLabel();
        cboThanhToan = new javax.swing.JComboBox<>();
        lblGhiChuThanhToan = new javax.swing.JLabel();
        txtGhiChuThanhToan = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel13 = new javax.swing.JPanel();
        lblTongTienKhachTra = new javax.swing.JLabel();
        txtTongThanhToan = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        btnInHoaDon = new javax.swing.JButton();
        btnHuyBo = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HÓA ĐƠN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 212;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 384, 24, 405);
        jPanel1.add(jLabel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Ngày check-in :");
        jLabel8.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel4.add(jLabel8);

        jdcCheckIn.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel4.add(jdcCheckIn);

        txtGioCheckIn.setEditable(false);
        txtGioCheckIn.setPreferredSize(new java.awt.Dimension(33, 33));
        jPanel4.add(txtGioCheckIn);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText(":");
        jPanel4.add(jLabel3);

        txtPhutCheckIn.setEditable(false);
        txtPhutCheckIn.setPreferredSize(new java.awt.Dimension(33, 33));
        jPanel4.add(txtPhutCheckIn);

        jdcCheckOut.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel4.add(jdcCheckOut);

        txtGioCheckOut.setEditable(false);
        txtGioCheckOut.setPreferredSize(new java.awt.Dimension(33, 33));
        jPanel4.add(txtGioCheckOut);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText(":");
        jPanel4.add(jLabel4);

        txtPhutCheckOut.setEditable(false);
        txtPhutCheckOut.setPreferredSize(new java.awt.Dimension(33, 33));
        jPanel4.add(txtPhutCheckOut);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 18, 1060, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tên khách hàng :");
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel5.add(jLabel2);

        txtTenKhachHang.setEditable(false);
        txtTenKhachHang.setPreferredSize(new java.awt.Dimension(320, 33));
        jPanel5.add(txtTenKhachHang);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Quốc tịch :");
        jLabel9.setPreferredSize(new java.awt.Dimension(90, 33));
        jPanel5.add(jLabel9);

        txtQuocTich.setEditable(false);
        txtQuocTich.setPreferredSize(new java.awt.Dimension(150, 33));
        jPanel5.add(txtQuocTich);

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1060, 40));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblCMT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCMT.setText("Số cmt/ Hộ chiếu :");
        lblCMT.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel15.add(lblCMT);

        txtSoCMT.setEditable(false);
        txtSoCMT.setPreferredSize(new java.awt.Dimension(320, 33));
        jPanel15.add(txtSoCMT);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Giới tính :");
        jLabel10.setPreferredSize(new java.awt.Dimension(90, 33));
        jPanel15.add(jLabel10);

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboGioiTinh.setPreferredSize(new java.awt.Dimension(150, 33));
        jPanel15.add(cboGioiTinh);

        jPanel2.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1030, -1));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Số diện thoại :");
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel16.add(jLabel5);

        txtSoDT.setEditable(false);
        txtSoDT.setPreferredSize(new java.awt.Dimension(320, 33));
        jPanel16.add(txtSoDT);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Ngày sinh :");
        jLabel11.setPreferredSize(new java.awt.Dimension(90, 33));
        jPanel16.add(jLabel11);

        jdcNgaySinh.setPreferredSize(new java.awt.Dimension(150, 33));
        jPanel16.add(jdcNgaySinh);

        jPanel2.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1040, -1));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Quê Quán/ Địa chỉ :");
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel17.add(jLabel6);

        txtQueQuan.setEditable(false);
        txtQueQuan.setPreferredSize(new java.awt.Dimension(320, 33));
        jPanel17.add(txtQueQuan);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setText("Hình thức :");
        jLabel35.setPreferredSize(new java.awt.Dimension(90, 33));
        jPanel17.add(jLabel35);

        chkTheoNgay.setBackground(new java.awt.Color(255, 255, 255));
        chkTheoNgay.setText("theo ngày");
        jPanel17.add(chkTheoNgay);

        chkTheoGio.setBackground(new java.awt.Color(255, 255, 255));
        chkTheoGio.setText("Theo giờ");
        jPanel17.add(chkTheoGio);

        jPanel2.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 1050, -1));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Email :");
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel18.add(jLabel7);

        txtEmail.setEditable(false);
        txtEmail.setPreferredSize(new java.awt.Dimension(320, 33));
        jPanel18.add(txtEmail);

        jPanel2.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 1050, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel12.setText("Số phòng :");

        tblThongTinPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblThongTinPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Check-In", "Check-Out", "Hình thức thuê", "Giá", "Thời gian ở tại", "Loại phòng"
            }
        ));
        tblThongTinPhong.setRowHeight(30);
        tblThongTinPhong.setShowHorizontalLines(false);
        tblThongTinPhong.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblThongTinPhong);
        if (tblThongTinPhong.getColumnModel().getColumnCount() > 0) {
            tblThongTinPhong.getColumnModel().getColumn(0).setMinWidth(150);
            tblThongTinPhong.getColumnModel().getColumn(1).setMinWidth(150);
            tblThongTinPhong.getColumnModel().getColumn(3).setResizable(false);
            tblThongTinPhong.getColumnModel().getColumn(4).setResizable(false);
        }

        txtSoPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSoPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSoPhong.setText("107");
        txtSoPhong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSoPhong.setPreferredSize(new java.awt.Dimension(45, 33));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Tầng : ");

        txtSoTang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSoTang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSoTang.setText("2");
        txtSoTang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSoTang.setPreferredSize(new java.awt.Dimension(33, 33));

        tblTongTienDichVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblTongTienDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Dịch vụ", "Thời gian gọi", "Tổng phí dịch vụ"
            }
        ));
        tblTongTienDichVu.setRowHeight(30);
        tblTongTienDichVu.setShowHorizontalLines(false);
        tblTongTienDichVu.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tblTongTienDichVu);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5);
        flowLayout1.setAlignOnBaseline(true);
        jPanel8.setLayout(flowLayout1);

        lblTongTienPhong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTongTienPhong.setText("Tổng tiền phòng :");
        lblTongTienPhong.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel8.add(lblTongTienPhong);

        txtTienTheoGio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTienTheoGio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtTienTheoGio.setPreferredSize(new java.awt.Dimension(150, 33));
        jPanel8.add(txtTienTheoGio);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("X");
        jPanel8.add(jLabel16);

        txtSoGio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSoGio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtSoGio.setPreferredSize(new java.awt.Dimension(99, 33));
        jPanel8.add(txtSoGio);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("+");
        jPanel8.add(jLabel24);

        txtTienTheoNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTienTheoNgay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtTienTheoNgay.setPreferredSize(new java.awt.Dimension(150, 33));
        jPanel8.add(txtTienTheoNgay);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("X");
        jPanel8.add(jLabel20);

        txtSoNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSoNgay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtSoNgay.setPreferredSize(new java.awt.Dimension(99, 33));
        jPanel8.add(txtSoNgay);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("=");
        jPanel8.add(jLabel26);

        txtTongTienPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTongTienPhong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtTongTienPhong.setPreferredSize(new java.awt.Dimension(185, 33));
        jPanel8.add(txtTongTienPhong);

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1072, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5);
        flowLayout2.setAlignOnBaseline(true);
        jPanel9.setLayout(flowLayout2);

        lblTongTienDV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTongTienDV.setText("Tổng tiền dịch vụ :");
        lblTongTienDV.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel9.add(lblTongTienDV);

        txtTongTienDichVu.setEditable(false);
        txtTongTienDichVu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTongTienDichVu.setPreferredSize(new java.awt.Dimension(150, 33));
        jPanel9.add(txtTongTienDichVu);

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1072, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5);
        flowLayout3.setAlignOnBaseline(true);
        jPanel10.setLayout(flowLayout3);

        lblTongPhiPhuThu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTongPhiPhuThu.setText("Phí phụ thu :");
        lblTongPhiPhuThu.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel10.add(lblTongPhiPhuThu);

        txtPhiPhuThu.setEditable(false);
        txtPhiPhuThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPhiPhuThu.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel10.add(txtPhiPhuThu);

        lblPhiTraPhongMuon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhiTraPhongMuon.setText("Phí trả phòng muộn :");
        jPanel10.add(lblPhiTraPhongMuon);

        txtPhiTraPMuon.setEditable(false);
        txtPhiTraPMuon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPhiTraPMuon.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel10.add(txtPhiTraPMuon);

        lblPhiNhanPhongSom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhiNhanPhongSom.setText("Phí nhận phòng sớm :");
        jPanel10.add(lblPhiNhanPhongSom);

        txtPhiNhanPSom.setEditable(false);
        txtPhiNhanPSom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPhiNhanPSom.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel10.add(txtPhiNhanPSom);

        lblPhiDVNgayLe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhiDVNgayLe.setText("Phí dịch vụ ngày lễ :");
        jPanel10.add(lblPhiDVNgayLe);

        cboPhiDVNgayLe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPhiDVNgayLe.setPreferredSize(new java.awt.Dimension(120, 33));
        cboPhiDVNgayLe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPhiDVNgayLeItemStateChanged(evt);
            }
        });
        jPanel10.add(cboPhiDVNgayLe);

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1072, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout4 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5);
        flowLayout4.setAlignOnBaseline(true);
        jPanel11.setLayout(flowLayout4);

        lblKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKhuyenMai.setText("Khuyến mãi :");
        lblKhuyenMai.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel11.add(lblKhuyenMai);

        cboKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cboKhuyenMai.setPreferredSize(new java.awt.Dimension(120, 33));
        cboKhuyenMai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboKhuyenMaiItemStateChanged(evt);
            }
        });
        jPanel11.add(cboKhuyenMai);

        lblTraTruoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTraTruoc.setText("Trả Trước  :");
        jPanel11.add(lblTraTruoc);

        txtTraTruoc.setEditable(false);
        txtTraTruoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTraTruoc.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel11.add(txtTraTruoc);

        lblGiamGia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblGiamGia.setText("Giảm giá :");
        jPanel11.add(lblGiamGia);

        txtGiamGia.setEditable(false);
        txtGiamGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtGiamGia.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel11.add(txtGiamGia);

        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1072, -1));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout5 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5);
        flowLayout5.setAlignOnBaseline(true);
        jPanel12.setLayout(flowLayout5);

        lblLoaiThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLoaiThanhToan.setText("Loại thanh toán :");
        lblLoaiThanhToan.setPreferredSize(new java.awt.Dimension(120, 33));
        jPanel12.add(lblLoaiThanhToan);

        cboThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cboThanhToan.setPreferredSize(new java.awt.Dimension(180, 33));
        jPanel12.add(cboThanhToan);

        lblGhiChuThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGhiChuThanhToan.setText("Ghi chú :");
        jPanel12.add(lblGhiChuThanhToan);

        txtGhiChuThanhToan.setPreferredSize(new java.awt.Dimension(450, 33));
        jPanel12.add(txtGhiChuThanhToan);

        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1048, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 51, 153));
        jSeparator1.setOpaque(true);
        jPanel7.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 1048, 10));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout6 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout6.setAlignOnBaseline(true);
        jPanel13.setLayout(flowLayout6);

        lblTongTienKhachTra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTongTienKhachTra.setText("Tổng tiền khách phải trả :");
        jPanel13.add(lblTongTienKhachTra);

        txtTongThanhToan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTongThanhToan.setForeground(new java.awt.Color(204, 0, 204));
        txtTongThanhToan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtTongThanhToan.setPreferredSize(new java.awt.Dimension(270, 30));
        jPanel13.add(txtTongThanhToan);

        jPanel7.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 1048, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(txtSoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSoTang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSoTang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout7 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5);
        flowLayout7.setAlignOnBaseline(true);
        jPanel14.setLayout(flowLayout7);

        btnInHoaDon.setBackground(new java.awt.Color(0, 204, 204));
        btnInHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_insert_25px.png"))); // NOI18N
        btnInHoaDon.setText("In Hóa đơn");
        btnInHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInHoaDonActionPerformed(evt);
            }
        });
        jPanel14.add(btnInHoaDon);

        btnHuyBo.setBackground(new java.awt.Color(0, 204, 204));
        btnHuyBo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuyBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_cancel_25px.png"))); // NOI18N
        btnHuyBo.setText("Hủy bỏ");
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });
        jPanel14.add(btnHuyBo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
        // TODO add your handling code here:
        TraPhongJframe frame = (TraPhongJframe) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
    }//GEN-LAST:event_btnHuyBoActionPerformed

    private void btnInHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInHoaDonActionPerformed
        // TODO add your handling code here:
        if (mgsBox.confirm(this, "Bạn có chắc muốn in hóa đơn..?")) {
            inHoaDon();
        }
    }//GEN-LAST:event_btnInHoaDonActionPerformed

    private void cboPhiDVNgayLeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPhiDVNgayLeItemStateChanged
        // TODO add your handling code here:
        try {
            String chose = (String) cboPhiDVNgayLe.getSelectedItem();
            char[] ch = chose.toCharArray();
            String choose_val = "";
            for (int i = 0; i < ch.length; i++) {
                if (ch[i] != '%') {
                    choose_val += ch[i];
                }
            }
            try {
                int num_val = Integer.parseInt(choose_val);
                tienPhucVuNGayLe = num_val;
                KhachPhaiTra();
            } catch (NumberFormatException e) {
                e.printStackTrace();
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cboPhiDVNgayLeItemStateChanged

    private void cboKhuyenMaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboKhuyenMaiItemStateChanged
        // TODO add your handling code here:
        try {
            String chose = (String) cboKhuyenMai.getSelectedItem();
            char[] ch = chose.toCharArray();
            String choose_val = "";
            for (int i = 0; i < ch.length; i++) {
                if (ch[i] != '%') {
                    choose_val += ch[i];
                }
            }
            try {
                int num_val = Integer.parseInt(choose_val);
                tienKhuyenMai = num_val;
                KhachPhaiTra();
            } catch (NumberFormatException e) {
                e.printStackTrace();
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cboKhuyenMaiItemStateChanged

    public void init() {
        lichSuGDDAO = new LichSuGDDAO();
        khachHangDAO = new KhachHangDAO();
        hoaDonDAO = new HoaDonDAO();
        hoaDonChiTietDAO = new HoaDonChiTietDAO();
        lsgddao = new LichSuGDDAO();
        phongDAO = new PhongDAO();
        loaiPhongDAO = new LoaiPhongDAO();
        yeuCauDAO = new YeuCauDAO();
        dichVuDAO = new DichVuDAO();
        loaiThanhToanDAO = new LoaiThanhToanDAO();
        thanhToanDAO = new ThanhToanDAO();
        sumHour = 0;
        sumDay = 0;
        sumMinute = 0;
        tienTraCham = 0;
        sumMoneyService = 0;
        tienVaoSom = 0;
        tienTraTruoc = 0;
        tienKhuyenMai = 0;
        tienPhucVuNGayLe = 0;
        tienGiamGia = 0;
        tienPhuThu = 0;
        sumMoneyHavePay = 0;
        KhachHang kh = khachHangDAO.selectById(maKH);
        fillForm(kh);
        fillTangAndPhong();
        fillHoaDonField(maKH);
        fillGioiTinh();
        fillPhiDVNgayLe();
        fillPhiKhuyenMai();
        fillTableThongTinPhong();
        fillTableThongTinDV();
        fillThanhToan();
        TinhTienPhong();
        tinhTienDichVu();
        KhachPhaiTra();
    }

    public void fillForm(KhachHang kh) {
        txtSoCMT.setText(kh.getSoCMT());
        txtTenKhachHang.setText(kh.getHoTen());
        txtSoDT.setText(kh.getSoDT());
        jdcNgaySinh.setDate(kh.getNgaySinh());
        txtQueQuan.setText(kh.getQueQuan());
        txtQuocTich.setText(kh.getQuocTich());
        txtEmail.setText(kh.getEmail());
        if (kh.isGioiTinh()) {
            cboGioiTinh.setSelectedIndex(0);
        } else {
            cboGioiTinh.setSelectedIndex(1);
        }
    }

    public void fillTangAndPhong() {
        txtSoTang.setText(String.valueOf(MapRoom.posTang));
        txtSoPhong.setText(String.valueOf(MapRoom.posPhong));
    }

    public void fillHoaDonField(int maKH) {

        HoaDon hd = hoaDonDAO.selectHoaDonByKH(maKH, false);
        jdcCheckIn.setDate(hd.getThoiDiemDatPhong());
        xTime.getTimeFromDatabase(hd.getThoiDiemDatPhong(), txtGioCheckIn, txtPhutCheckIn);
        if (hd.getThoiDiemTraPhong() != null) {
            jdcCheckOut.setDate(hd.getThoiDiemTraPhong());
            xTime.getTimeFromDatabase(hd.getThoiDiemTraPhong(), txtGioCheckOut, txtPhutCheckOut);
        } else {
            Timestamp localDate = new Timestamp(System.currentTimeMillis());
            jdcCheckOut.setDate(localDate);
            xTime.getTimeFromDatabase(localDate, txtGioCheckOut, txtPhutCheckOut);
        }
        try {
            int maHDCT = hoaDonChiTietDAO.selectByNewIDReserve(false, MapRoom.posTang, MapRoom.posPhong).getMaCTHD();
            List<LichSuGD> ls = lsgddao.selectByMaHDCT(maHDCT);
            if (ls.get(0).isTrangThai()) {
                chkTheoGio.setSelected(true);
            } else {
                chkTheoNgay.setSelected(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        tienPhuThu = hd.getPhuThu();
        tienTraTruoc = hd.getTienTraTruoc();
        tienGiamGia = hd.getGiamGia();
        txtTraTruoc.setText(xMoney.doubleToVNDong(tienTraTruoc));
        txtPhiPhuThu.setText(xMoney.doubleToVNDong(tienPhuThu));
        txtGiamGia.setText(xMoney.doubleToVNDong(tienGiamGia));
    }

    public void fillGioiTinh() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboGioiTinh.getModel();
        model.removeAllElements();
        model.addElement("Nam");
        model.addElement("Nữ");
    }

    public void fillPhiDVNgayLe() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboPhiDVNgayLe.getModel();
        model.removeAllElements();
        model.addElement("0%");
        model.addElement("10%");
        model.addElement("20%");
        model.addElement("30%");
        model.addElement("50%");
    }

    public void fillPhiKhuyenMai() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboKhuyenMai.getModel();
        model.removeAllElements();
        model.addElement("0%");
        model.addElement("10%");
        model.addElement("20%");
        model.addElement("30%");
        model.addElement("50%");
    }

    public void fillThanhToan() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboThanhToan.getModel();
        model.removeAllElements();
        try {
            List<LoaiThanhToan> ltt = loaiThanhToanDAO.selectAll();
            System.out.println(ltt);
            for (LoaiThanhToan loaiThanhToan : ltt) {
                model.addElement(loaiThanhToan);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void fillTableThongTinPhong() {
        DefaultTableModel model = (DefaultTableModel) tblThongTinPhong.getModel();
        model.setRowCount(0);
        try {
            int maHDCT = hoaDonChiTietDAO.selectByNewIDReserve(false, MapRoom.posTang, MapRoom.posPhong).getMaCTHD();
            int maLoaiPhong = phongDAO.selectByIdd(MapRoom.posTang, MapRoom.posPhong).getMaLoaiPhong();
            String TenLoaiPhong = loaiPhongDAO.selectById(maLoaiPhong).getTenLP();
            double giaGio = loaiPhongDAO.selectById(maLoaiPhong).getGiaGio();
            double giaNgay = loaiPhongDAO.selectById(maLoaiPhong).getGiaNgay();
            List<LichSuGD> ls = lsgddao.selectByMaHDCT(maHDCT);
            for (LichSuGD l : ls) {
                Object[] lsGio = lsgddao.getTimesRented(l.getThoiGianBD(), l.getThoiGianKT()).get(0);
                System.out.println("lsgio: " + lsGio);
                int soNgay = Integer.parseInt(lsGio[0].toString());
                int soGio = Integer.parseInt(lsGio[1].toString());
                int soPhut = Integer.parseInt(lsGio[2].toString());
                String donVi = "";
                if (l.isTrangThai()) {
                    donVi = Math.abs(soGio) + "giờ " + Math.abs(soPhut) + " phút";
                } else {
                    if (soNgay == 0) {
                        donVi = "1 " + "Ngày";
                    } else {
                        donVi = "" + soNgay + " Ngày";
                    }
                }
                DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss");
                
                model.addRow(new Object[]{
                    dateFormat.format(l.getThoiGianBD()),
                    dateFormat.format(l.getThoiGianKT()),
                    l.isTrangThai() ? "Giờ" : "Ngày",
                    l.isTrangThai() ? xMoney.doubleToVNDong(giaGio) : xMoney.doubleToVNDong(giaNgay),
                    donVi,
                    TenLoaiPhong
                });
            }
        } catch (Exception e) {
            mgsBox.alert(this, "Có lỗi xảy ra");
            e.printStackTrace();
        }

    }

    public void fillTableThongTinDV() {
        DefaultTableModel model = (DefaultTableModel) tblTongTienDichVu.getModel();
        model.setRowCount(0);
        List<Object[]> ls = yeuCauDAO.getDichVuDaDung(MapRoom.posTang, MapRoom.posPhong);
        for (Object[] l : ls) {
            BigDecimal bd = (BigDecimal) l[2]; // the value you get
            double d = bd.doubleValue();
            model.addRow(new Object[]{
                l[0], l[1], xMoney.doubleToVNDong(d)
            });
        }
    }

    public void TinhTienPhong() {
        try {
            int maHDCT = hoaDonChiTietDAO.selectByNewIDReserve(false, MapRoom.posTang, MapRoom.posPhong).getMaCTHD();
            int maLoaiPhong = phongDAO.selectByIdd(MapRoom.posTang, MapRoom.posPhong).getMaLoaiPhong();
            double giaGio = loaiPhongDAO.selectById(maLoaiPhong).getGiaGio();
            double giaNgay = loaiPhongDAO.selectById(maLoaiPhong).getGiaNgay();

            List<LichSuGD> ls = lsgddao.selectByMaHDCT(maHDCT);
            Timestamp ngayCheckInHol = xTime.getTimeHol(ls.get(ls.size() - 1).getThoiGianBD(), 14, 0);
            Timestamp ngayCheckOutHol = xTime.getTimeHol(ls.get(0).getThoiGianKT(), 12, 0);
            if (ls.get(0).isTrangThai() == false) {
                Object[] tienVoSom = yeuCauDAO.getTienNhanPSom(ls.get(ls.size() - 1).getThoiGianBD(), ngayCheckInHol, giaNgay).get(0);
                tienVaoSom = Double.parseDouble(tienVoSom[0].toString());
                Object[] tienTre = yeuCauDAO.getTienTraPTre(ls.get(0).getThoiGianKT(), ngayCheckOutHol, giaNgay).get(0);
                tienTraCham = Double.parseDouble(tienTre[0].toString());
            }
            for (LichSuGD l : ls) {
                Object[] lsGio = lsgddao.getTimesRented(l.getThoiGianBD(), l.getThoiGianKT()).get(0);
                int soNgay = Integer.parseInt(lsGio[0].toString());
                int soGio = Integer.parseInt(lsGio[1].toString());
                int soPhut = Integer.parseInt(lsGio[2].toString());
                if (l.isTrangThai()) {
                    sumHour += soGio;
                    sumMinute += soPhut;
                } else {
                    if (soNgay == 0) {
                        sumDay = 1;
                    } else {
                        sumDay += soNgay;
                    }
                }
            }
            if (sumMinute > 30) {
                sumHour++;
            } else if (sumMinute > 5) {
                sumHour += 0.5;
            }

            sumMoneyRoom = giaNgay * sumDay + giaGio * sumHour;

            txtSoGio.setText(String.valueOf(sumHour) + " giờ");
            txtSoNgay.setText(String.valueOf(sumDay) + " ngày");
            txtTienTheoGio.setText(xMoney.doubleToVNDong(giaGio));
            txtTienTheoNgay.setText(xMoney.doubleToVNDong(giaNgay));
            txtTongTienPhong.setText(xMoney.doubleToVNDong(sumMoneyRoom));
            txtPhiNhanPSom.setText(xMoney.doubleToVNDong(tienVaoSom));
            txtPhiTraPMuon.setText(xMoney.doubleToVNDong(tienTraCham));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void tinhTienDichVu() {
        List<Object[]> ls = yeuCauDAO.getDichVuDaDung(MapRoom.posTang, MapRoom.posPhong);
        for (int i = 0; i < ls.size(); i++) {
            Object[] dv = ls.get(i);
            sumMoneyService += Double.parseDouble(dv[2].toString());
        }
        txtTongTienDichVu.setText(xMoney.doubleToVNDong(sumMoneyService));
    }

    public void KhachPhaiTra() {
        try {
            sumMoneyHavePay = sumMoneyRoom + sumMoneyService + tienTraCham + tienVaoSom + tienPhuThu - tienTraTruoc - tienGiamGia;
            sumMoneyHavePay = sumMoneyHavePay + sumMoneyHavePay * (tienPhucVuNGayLe / 100) - sumMoneyHavePay * (tienKhuyenMai / 100);
            txtTongThanhToan.setText(xMoney.doubleToVNDong(sumMoneyHavePay));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void inHoaDon() {
        HoaDon hd = hoaDonDAO.selectHoaDonByKH(maKH, false);
        // chuyen hoa don chi tiet ve trang thai dathanhtoan
        hoaDonChiTietDAO.updateV1(true, MapRoom.posPhong, MapRoom.posTang, false);
        //chuyen trang thai phong ve trang thai dang don dep
        phongDAO.updateMaTT(new Phong(MapRoom.posPhong, MapRoom.posTang, 1, 5, null));
        mgsBox.alert(this, "In Hóa đơn thành công.");

        try {
            HoaDonChiTiet hdct = hoaDonChiTietDAO.selectByNewID(hd.getMaHD(), false);
            hd.setTienTraTruoc(0);
            themThanhToan(hd.getMaHD());
            themTongTien(hd);
        } catch (Exception e) {
            System.out.println("Hóa đơn cuối rồi");
            e.printStackTrace();
            hoaDonDAO.updateTT(true, hd.getMaHD());
            themThanhToan(hd.getMaHD());
            themTongTien(hd);
        }
        MapRoom.maKH = 0;
        TraPhongJframe frame = (TraPhongJframe) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
    }

    public void themTongTien(HoaDon hd) {
        try {
            double tongTienDatabase = hd.getThanhTien();
            double tongTienHT = tongTienDatabase + sumMoneyHavePay;
            System.out.println("mahd: " + hd.getMaHD() + " , tongtiendatabase: " + tongTienDatabase + ", tongtien ht: " + tongTienHT);
            hoaDonDAO.updateTongTien(hd.getTienTraTruoc(), tongTienHT, hd.getMaHD());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void themThanhToan(int mahd) {
        try {
            Timestamp localDate = new Timestamp(System.currentTimeMillis());
            LoaiThanhToan maloaitt = (LoaiThanhToan) cboThanhToan.getSelectedItem();
            thanhToanDAO.insert(new ThanhToan(mahd, maloaitt.getLoaiThanhToan(), localDate, txtGhiChuThanhToan.getText()));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyBo;
    private javax.swing.JButton btnInHoaDon;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private javax.swing.JComboBox<String> cboKhuyenMai;
    private javax.swing.JComboBox<String> cboPhiDVNgayLe;
    private javax.swing.JComboBox<String> cboThanhToan;
    private javax.swing.JCheckBox chkTheoGio;
    private javax.swing.JCheckBox chkTheoNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser jdcCheckIn;
    private com.toedter.calendar.JDateChooser jdcCheckOut;
    private com.toedter.calendar.JDateChooser jdcNgaySinh;
    private javax.swing.JLabel lblCMT;
    private javax.swing.JLabel lblGhiChuThanhToan;
    private javax.swing.JLabel lblGiamGia;
    private javax.swing.JLabel lblKhuyenMai;
    private javax.swing.JLabel lblLoaiThanhToan;
    private javax.swing.JLabel lblPhiDVNgayLe;
    private javax.swing.JLabel lblPhiNhanPhongSom;
    private javax.swing.JLabel lblPhiTraPhongMuon;
    private javax.swing.JLabel lblTongPhiPhuThu;
    private javax.swing.JLabel lblTongTienDV;
    private javax.swing.JLabel lblTongTienKhachTra;
    private javax.swing.JLabel lblTongTienPhong;
    private javax.swing.JLabel lblTraTruoc;
    private javax.swing.JTable tblThongTinPhong;
    private javax.swing.JTable tblTongTienDichVu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGhiChuThanhToan;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtGioCheckIn;
    private javax.swing.JTextField txtGioCheckOut;
    private javax.swing.JTextField txtPhiNhanPSom;
    private javax.swing.JTextField txtPhiPhuThu;
    private javax.swing.JTextField txtPhiTraPMuon;
    private javax.swing.JTextField txtPhutCheckIn;
    private javax.swing.JTextField txtPhutCheckOut;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtQuocTich;
    private javax.swing.JTextField txtSoCMT;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JLabel txtSoGio;
    private javax.swing.JLabel txtSoNgay;
    private javax.swing.JLabel txtSoPhong;
    private javax.swing.JLabel txtSoTang;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JLabel txtTienTheoGio;
    private javax.swing.JLabel txtTienTheoNgay;
    private javax.swing.JLabel txtTongThanhToan;
    private javax.swing.JTextField txtTongTienDichVu;
    private javax.swing.JLabel txtTongTienPhong;
    private javax.swing.JTextField txtTraTruoc;
    // End of variables declaration//GEN-END:variables
}
